/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components.fields;

import java.util.List;

/**
 *
 * @author korisnik
 */
public class PanelInputComboBox extends Panel{

    /**
     * Creates new form PanelInputComboBox
     */
    public PanelInputComboBox() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFieldInput = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        cbField = new javax.swing.JComboBox<>();

        lblFieldInput.setText("jLabel1");

        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setText("jLabel2");

        cbField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFieldInput)
                .addGap(50, 50, 50)
                .addComponent(cbField, 0, 219, Short.MAX_VALUE))
            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFieldInput)
                    .addComponent(cbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError))
        );
    }// </editor-fold>//GEN-END:initComponents
private void prepareView() {
        cbField.removeAllItems();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbField;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFieldInput;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getValue() {
        return cbField.getSelectedItem();
    }

    @Override
    public void initialize(Object initValue) {
        List<String> items = (List<String>) initValue;
        for (String item : items) {
            cbField.addItem(item);
        }
    }
    
    @Override
    public void setLabels(String lbl1, String lbl2){
        lblFieldInput.setText(lbl1);
        lblError.setText(lbl2);
    }
}
