/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components.fields;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author korisnik
 */
public class PanelInputDateCombobox extends Panel{

    /**
     * Creates new form PanelInputDateCheckbox
     */
    public PanelInputDateCombobox() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        lblFieldText = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        cbFieldDay = new javax.swing.JComboBox<>();
        cbFieldMonth = new javax.swing.JComboBox<>();
        cbFieldYear = new javax.swing.JComboBox<>();

        jCheckBox3.setText("jCheckBox3");

        lblFieldText.setText("jLabel1");

        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setText("jLabel2");

        cbFieldDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbFieldMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbFieldYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFieldText)
                .addGap(71, 71, 71)
                .addComponent(cbFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFieldText)
                    .addComponent(cbFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError))
        );
    }// </editor-fold>//GEN-END:initComponents
public void prepareView(){
        cbFieldDay.removeAllItems();
        cbFieldMonth.removeAllItems();
        cbFieldYear.removeAllItems();
        
        for (int i = 1; i < 32; i++) {
            cbFieldDay.addItem(i+"");
    }
        for (int i = 1; i < 13; i++) {
            cbFieldMonth.addItem(i+"");
    }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
        Date date = new Date();
        int year = Integer.parseInt(sdf.format(date));
        
        for (int i = 1950; i < year; i++) {
            cbFieldYear.addItem(i+"");
    }
}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbFieldDay;
    private javax.swing.JComboBox<String> cbFieldMonth;
    private javax.swing.JComboBox<String> cbFieldYear;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFieldText;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getValue() {
        String day = (String)cbFieldDay.getSelectedItem();
        String month = (String)cbFieldMonth.getSelectedItem();
        String year = (String)cbFieldYear.getSelectedItem();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            return sdf.parse(day + "/" + month + "/" + year);
        } catch (ParseException ex) {
            return "n/a";
        }
    }

    @Override
    public void initialize(Object initValue) {
        List<String> items = (List<String>) initValue;
        lblFieldText.setText(items.get(0));
        lblError.setText(items.get(1));
    }

    @Override
    public void setLabels(String lbl1, String lbl2) {
        lblFieldText.setText(lbl1);
        lblError.setText(lbl2);
    }
}
