/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components.fields;

import java.util.List;
import javax.swing.ButtonGroup;

/**
 *
 * @author korisnik
 */
public class PanelInputRadioButton extends Panel{

    /**
     * Creates new form PanelInputRadioButton
     */
    public PanelInputRadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFieldText = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        rbField1 = new javax.swing.JRadioButton();
        rbField2 = new javax.swing.JRadioButton();

        lblFieldText.setText("jLabel1");

        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setText("jLabel2");

        rbField1.setText("jRadioButton1");

        rbField2.setText("jRadioButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFieldText)
                .addGap(42, 42, 42)
                .addComponent(rbField1)
                .addGap(18, 18, 18)
                .addComponent(rbField2))
            .addComponent(lblError)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFieldText)
                    .addComponent(rbField1)
                    .addComponent(rbField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFieldText;
    private javax.swing.JRadioButton rbField1;
    private javax.swing.JRadioButton rbField2;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getValue() {
        if (rbField1.isSelected()) return rbField1.getText();
        if (rbField2.isSelected()) return rbField2.getText();
        
        return null;
    }

    @Override
    public void initialize(Object initValue) {
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbField1);
        bg.add(rbField2);
        bg.clearSelection();
        List<String> items = (List<String>) initValue;
        rbField1.setText(items.get(0));
        rbField2.setText(items.get(1));
        rbField1.setSelected(true);
        
    }

    @Override
    public void setLabels(String lbl1, String lbl2) {
        lblFieldText.setText(lbl1);
        lblError.setText(lbl2);
    }
}
