/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components.fields;

import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author korisnik
 */
public class PanelInputTextBox extends Panel{

    /**
     * Creates new form PanelInputTextBox
     */
    public PanelInputTextBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFieldText = new javax.swing.JLabel();
        txtInputField = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();

        lblFieldText.setText("jLabel1");

        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFieldText)
                .addGap(18, 18, 18)
                .addComponent(txtInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFieldText)
                    .addComponent(txtInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblError))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblError() {
        return lblError;
    }

    public void setLblError(JLabel lblError) {
        this.lblError = lblError;
    }

    public JLabel getLblFieldText() {
        return lblFieldText;
    }

    public void setLblFieldText(JLabel lblFieldText) {
        this.lblFieldText = lblFieldText;
    }

    public JTextField getTxtInputField() {
        return txtInputField;
    }

    public void setTxtInputField(JTextField txtInputField) {
        this.txtInputField = txtInputField;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFieldText;
    private javax.swing.JTextField txtInputField;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getValue() {
        return txtInputField.getText();
    }

    @Override
    public void initialize(Object initValue) {
        List<String> values = (List<String>) initValue;
        lblFieldText.setText(values.get(0));
        //txtInputField.setText(values.get(1));
        lblError.setText(values.get(1));
    }

    @Override
    public void setLabels(String lbl1, String lbl2) {
        lblFieldText.setText(lbl1);
        lblError.setText(lbl2);
    }
}
