/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domain.FinalForms;
import domain.Form;
import javax.swing.JOptionPane;

/**
 *
 * @author korisnik
 */
public class FrmStart extends javax.swing.JFrame {

    
    public FrmStart() {
        initComponents();
        this.setTitle("Start");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuConfiguration = new javax.swing.JMenu();
        menuConfigurationItemCreate = new javax.swing.JMenuItem();
        menuForm = new javax.swing.JMenu();
        menuFormItemF1 = new javax.swing.JMenuItem();
        menuFormItemF2 = new javax.swing.JMenuItem();
        menuFormItemF3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuConfiguration.setText("Configuration");

        menuConfigurationItemCreate.setText("Create");
        menuConfigurationItemCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfigurationItemCreateActionPerformed(evt);
            }
        });
        menuConfiguration.add(menuConfigurationItemCreate);

        jMenuBar1.add(menuConfiguration);

        menuForm.setText("Form");

        menuFormItemF1.setText("F1");
        menuFormItemF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormItemF1ActionPerformed(evt);
            }
        });
        menuForm.add(menuFormItemF1);

        menuFormItemF2.setText("F2");
        menuFormItemF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormItemF2ActionPerformed(evt);
            }
        });
        menuForm.add(menuFormItemF2);

        menuFormItemF3.setText("F3");
        menuFormItemF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormItemF3ActionPerformed(evt);
            }
        });
        menuForm.add(menuFormItemF3);

        jMenuBar1.add(menuForm);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConfigurationItemCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfigurationItemCreateActionPerformed
        new FrmConfiguration().setVisible(true);

    }//GEN-LAST:event_menuConfigurationItemCreateActionPerformed

    private void menuFormItemF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormItemF1ActionPerformed
        if (FinalForms.getF1() == null) {
            JOptionPane.showMessageDialog(null, "Form F1 hasn't been created!", "Message", HEIGHT);
        } else {
            FinalForms.getF1().setVisible(true);
        }
    }//GEN-LAST:event_menuFormItemF1ActionPerformed

    private void menuFormItemF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormItemF2ActionPerformed
        if (FinalForms.getF2() == null) {
            JOptionPane.showMessageDialog(null, "Form F2 hasn't been created!", "Message", HEIGHT);
        } else {
            FinalForms.getF2().setVisible(true);
        }
    }//GEN-LAST:event_menuFormItemF2ActionPerformed

    private void menuFormItemF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormItemF3ActionPerformed
        if (FinalForms.getF3() == null) {
            JOptionPane.showMessageDialog(null, "Form F3 hasn't been created!", "Message", HEIGHT);
        } else {
            FinalForms.getF3().setVisible(true);
        }
    }//GEN-LAST:event_menuFormItemF3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuConfiguration;
    private javax.swing.JMenuItem menuConfigurationItemCreate;
    private javax.swing.JMenu menuForm;
    private javax.swing.JMenuItem menuFormItemF1;
    private javax.swing.JMenuItem menuFormItemF2;
    private javax.swing.JMenuItem menuFormItemF3;
    // End of variables declaration//GEN-END:variables
}
